version: "3.9"
services:
  devportal:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=production
      - FRONTEND_PORT=9000
      - BACKEND_PORT=8080
    restart: unless-stopped
