version: '3.8'

services:
  web:
    build: .
    ports:
      - "9000:9000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=supersecretkey-change-in-prod-2025
    volumes:
      - db_data:/app/data

volumes:
  db_data: